export const COMPILERS = [
  {
    id: "segfault",
    displayName: "SegFault.ai",
    tagline: "The premier tool for writing morally reprehensible C++ code.",
    accentColor: "#00ff88",
    accentColorDim: "#001a0d",
    buttonLabel: "[ COMPILE ]",
    logoGlyph: "⚠",
    chaosMessages: [
      "Dereferencing null pointer at line 1...",
      "Allocating 47GB on the stack...",
      "Overwriting memory you don't own...",
      "Casting void* to pure hubris...",
      "Segmentation fault (core dumped)...",
      "Leaking memory like a career...",
      "Writing past the end of the array...",
      "Compiling your crimes against C++...",
      "Undefined behavior detected. Proceeding anyway.",
      "Stack smashing protector: disabled (vibes only)",
    ],
    progressBarBehavior: "crash",
    progressBarLabel: "Stack frames corrupted: [random %]",
    chaosDurationMs: 3200,
    statusBarText:
      "SegFault.ai v0.0.1-unstable  |  UB: Active  |  Memory: Leaking  |  Core: Dumped",
    outputHeaderLabel: "SEGFAULT REPORT",
    outputTextColor: "#00ff88",
    outputBg: "#050f05",
    endBadgeLabel: "CORE DUMPED",
    endBadgePulse: true,
    endBadgeTextColor: "#000000",
    outputGlitch: false,
  },
  {
    id: "gcc",
    displayName: "GCC",
    tagline: "It compiles your insecurities instead of your binaries.",
    accentColor: "#a78bfa",
    accentColorDim: "#1a0a2e",
    buttonLabel: "[ PROCESS ]",
    logoGlyph: "◈",
    chaosMessages: [
      "Are you sure you wrote this yourself?",
      "Cross-referencing with your previous work...",
      "Hmm. Interesting choice. Very interesting.",
      "Comparing against industry standards...",
      "This... reminds us of something. Can't say what.",
      "Compiling insecurities: 3 of 3 found.",
      "Running self-doubt diagnostics...",
      "Checking if you've considered a different career...",
      "Evaluating your relationship with recursion...",
      "We're not mad. We're just disappointed.",
    ],
    progressBarBehavior: "slow",
    progressBarLabel: "Insecurities compiled: [random number] / [slightly higher number]",
    chaosDurationMs: 3800,
    statusBarText:
      "GCC v∞  |  Binary: Unproduced  |  Feelings: Processed  |  Confidence: Low",
    outputHeaderLabel: "COMPILATION SUMMARY",
    outputTextColor: "#c4b5fd",
    outputBg: "#0d0a14",
    endBadgeLabel: "FEELINGS LOGGED",
    endBadgePulse: false,
    endBadgeTextColor: "#0d0a14",
    outputGlitch: false,
  },
  {
    id: "syntaxterror",
    displayName: "SyntaxTerror",
    tagline: "It doesn't find bugs; it creates them.",
    accentColor: "#ff1a75",
    accentColorDim: "#2a0015",
    buttonLabel: "[ TERRORIZE ]",
    logoGlyph: "☠",
    chaosMessages: [
      "Injecting race conditions...",
      "Randomizing your variable names...",
      "Adding off-by-one errors to every loop...",
      "Introducing subtle floating point drift...",
      "Swapping two random constants...",
      "Installing a memory leak (for performance)...",
      "Reversing your sort order...",
      "Commenting out your error handling...",
      "Making one import circular...",
      "Bug installation: COMPLETE. Enjoy.",
    ],
    progressBarBehavior: "frantic",
    progressBarLabel: "Bugs injected: [rapidly incrementing number]",
    chaosDurationMs: 2600,
    statusBarText:
      "SyntaxTerror v13  |  Bugs Created: [incrementing]  |  Bugs Fixed: 0  |  Chaos: MAX",
    outputHeaderLabel: "BUG REPORT (INSTALL LOG)",
    outputTextColor: "#ff1a75",
    outputBg: "#12000a",
    endBadgeLabel: "TERRORISM COMPLETE",
    endBadgePulse: true,
    endBadgeTextColor: "#000000",
    outputGlitch: true,
  },
];
